services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: neptunus
      POSTGRES_USER: ${NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports: 
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    environment: 
      SPRING_DATASOURCE_URL: ${URL}
      SPRING_DATASOURCE_USERNAME: ${NAME}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
      CODECOOL.APP.JWTSECRET: ${SECRET}
      CODECOOL.APP.JWTEXPIRATIONMS: ${EXPIRATION}
  
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
volumes: 
  postgres_data:

